### ISSUE TITLE
活动议程审核后发确认邮件

### ISSUE THREAD

**Issue by TechQuery** [kaiyuanshe/KYS-service#16]

**Comment by bestony** [comment]
<img width="943" alt="image" src="https://github.com/kaiyuanshe/KYS-service/assets/13283837/65f064be-dc0d-4710-8f5b-561ce67d4557">
实现了一个 demo

**Comment by bestony** [comment]
https://github.com/kaiyuanshe/KYS-service/assets/13283837/8ddbd810-fed9-4d3a-812d-6d4931b42ca4

@TechQuery 可以验收试一下～ 源码在：https://github.com/FeiShuio/Base-Email-Extension/

验收可用地址：`https://base-email-vue.vercel.app/`

**Comment by TechQuery** [comment]
@bestony 飞书多维表格最近内置了邮件发送：
![image](https://github.com/user-attachments/assets/06592bc5-492a-4aa5-b97a-6c208cc8328b)
![image](https://github.com/user-attachments/assets/be10b7a7-d347-4619-9242-8c0fa74bee99)
