### ISSUE TITLE
Integrate the backend APIs for KToken.

### ISSUE THREAD

**Issue by AmbitionCX** [kaiyuanshe/KYS-service#23]
The backend APIs for KToken can be found in this link: https://github.com/kaiyuanshe/KToken/blob/main/backend/scripts/contract.ts

Please integrate them into the Kaiyuanshe server.

**Comment by TechQuery** [comment]
@AmbitionCX 合约 JSON 文件没提交上来：
https://github.com/kaiyuanshe/KToken/blob/7ecd5618d6967b91168fa99ab5d2d48063e643f8/backend/scripts/contract.ts#L6

**Comment by TechQuery** [comment]
@AmbitionCX 现有接口无法实现 kaiyuanshe/kaiyuanshe.github.io#102 设计的功能。

**Comment by AmbitionCX** [comment]
当前接口可以实现 “My Token” 部分，即连接 Metamask 读取自己的积分。第二个 NFT 部分，目前还没做。第三个排名的部分，我在想是用后台数据库，还是直接放链上好（测试链可以放链上，如果上了主链就得考虑成本了）。

所以，先实现一下第一个部分即可。
