### ISSUE TITLE
管理后台界面

### ISSUE THREAD

**Issue by TechQuery** [kaiyuanshe/KYS-service#25]
## 开源依赖

https://github.com/dashpresshq/dashpress/blob/master/Dockerfile.example

## 更改目标

等待后端 API 服务启动并同步完数据库结构后，再启动管理后台容器连接数据库：

https://github.com/kaiyuanshe/KYS-service/blob/87913b92e2a5f9d21bb06afc961b3ecf9962d638/docker-compose.yml#L6-L30

**Comment by luojiyin1987** [comment]
https://github.com/dashpresshq/dashpress/pull/87 
为减少 Docker 镜像大小， 给上游提个了 PR

**Comment by luojiyin1987** [comment]
https://github.com/dashpresshq/dashpress/discussions/88   对上游提出 issue。
