### ISSUE TITLE
过往活动数据迁移

### ISSUE THREAD

**Issue by TechQuery** [kaiyuanshe/KYS-service#7]
讲师、议程数据迁移至[开放会务系统](https://kaiyuanshe.feishu.cn/wiki/wikcnuUsRHqJF0qhShySwECmWlx)。

## 历史数据

- COSCon：https://kaiyuanshe.feishu.cn/wiki/wikcnDsnNdHzty0TbfGTppfRBQb
- 其它小活动：

## 操作方法

- [x] 爬虫脚本
    - FreeCodeCamp-Chengdu/IT-events#1
    - FreeCodeCamp-Chengdu/IT-events#2
    - FreeCodeCamp-Chengdu/IT-events#3
- [x] 手工复制、粘贴
- [x] 图片 OCR 识别

**Comment by TechQuery** [comment]
@TechQuery 迁移文本，@PapayaHUANG 上传图片，共同完成 COSCon 2020 数据迁移：https://kaiyuanshe.cn/activity/recYi9rLaH

**Comment by TechQuery** [comment]
@PapayaHUANG 完成 COSCon 2022 数据迁移

https://kaiyuanshe.cn/activity/recNgZ1MiV

**Comment by PapayaHUANG** [comment]
@PapayaHUANG 完成COSCon 2021 数据迁移

https://kaiyuanshe.cn/activity/recoZ6PJXe

**Comment by TechQuery** [comment]
@PapayaHUANG 完成 COSCon 2017 数据迁移

https://kaiyuanshe.cn/activity/reciKhD1kz

**Comment by TechQuery** [comment]
@d-ethan3 完成 COSCon 2018 数据迁移

https://kaiyuanshe.cn/activity/reclGiXrsp

**Comment by TechQuery** [comment]
@Pear107 完成 COSCon 2016 数据迁移

https://kaiyuanshe.cn/activity/recTbkVCtB

**Comment by TechQuery** [comment]
@PapayaHUANG 完成 COSCon 2020 数据迁移

https://kaiyuanshe.cn/activity/recYi9rLaH

**Comment by TechQuery** [comment]
@PapayaHUANG @d-ethan3 完成 COSCon 2019 数据迁移

https://kaiyuanshe.cn/activity/recmgqmI54

**Comment by TechQuery** [comment]
@Pear107 完成 Apache RoadShow 2015 数据迁移

https://kaiyuanshe.cn/activity/reckOKSaJp
